export { default as Home } from './Home/Home'
export { default as Cart } from './Cart/Cart'
export { default as Auth } from './Auth/Auth'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
export { default as NewPassword } from './NewPassword/NewPassword'
export { default as ErrorPage } from './ErrorPage/ErrorPage'