export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
export const LOGOUT = 'auth/LOGOUT'
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS'
export const SET_ERROR = 'auth/SET_ERROR'
export const SET_IS_CHECKED = 'auth/SET_IS_CHECKED'
