export const SUCCESS_FETCHING_PRODUCTS = 'products/SUCCESS_FETCHING_PRODUCTS'
export const CLEAR_PRODUCTS = 'products/CLEAR_PRODUCTS'
export const SET_IS_LOADING = 'products/SET_IS_LOADING'
export const ERROR_FETCHING_PRODUCTS = 'products/ERROR_FETCHING_PRODUCTS'


